# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Client Name')),
                ('client_email', models.EmailField(max_length=200, verbose_name='Client Email')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Client Phone')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('postage_date', models.DateField(auto_now_add=True, verbose_name='Postage Date')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
        migrations.CreateModel(
            name='LetterSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Subject Title')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.LetterSubject', verbose_name='Subject'),
        ),
    ]
