# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Phone'),
        ),
    ]
