# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170814_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='client_email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='client_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
    ]
