# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails', verbose_name='Thumbnail'),
        ),
    ]
