# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170813_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=django_jalali.db.models.jDateField(verbose_name='Publish date'),
        ),
    ]
