# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 19:18
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170829_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Brief content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_status',
            field=models.BooleanField(default=True, verbose_name='Publish status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails', verbose_name='Thumbnail'),
        ),
    ]
