# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170829_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief_content',
            field=models.TextField(null=True, verbose_name='Brief content'),
        ),
    ]
